export const FORECAST_DAYS = [
  { key: "1", value: "1 Days forecast" },
  { key: "2", value: "2 Days forecast" },
  { key: "3", value: "3 Days forecast" },
  { key: "4", value: "4 Days forecast" },
  { key: "5", value: "5 Days forecast" },
  { key: "6", value: "6 Days forecast" },
  { key: "7", value: "7 Days forecast" },
  { key: "8", value: "8 Days forecast" },
  { key: "9", value: "9 Days forecast" },
  { key: "10", value: "10 Days forecast" },
  { key: "11", value: "11 Days forecast" },
  { key: "12", value: "12 Days forecast" },
  { key: "13", value: "13 Days forecast" },
  { key: "14", value: "14 Days forecast" },
];
