export const UPDATE_SEARCHED_KEYWORD = "UPDATE_SEARCHED_KEYWORD";
export const UPDATE_SEARCHED_CITIES = "UPDATE_SEARCHED_CITIES";
export const CLEAR_SEARCHED_CITY_REDUCER = "CLEAR_SEARCHED_CITY_REDUCER";
export const UPDATE_IS_SEARCH_LOADING = "UPDATE_IS_SEARCH_LOADING";
//----------------------------------------------------------------------------//
export const UPDATE_SELECTED_CITY = "UPDATE_SELECTED_CITY";
export const UPDATE_WEATHER_DETAILS = "UPDATE_WEATHER_DETAILS";
export const WEATHER_DETAILS_LOADER = "WEATHER_DETAILS_LOADER";
export const UPDATE_WEATHER_FORECAST_DETAILS =
  "UPDATE_WEATHER_FORECAST_DETAILS";
export const WEATHER_FORECAST_DETAILS_LOADER =
  "WEATHER_FORECAST_DETAILS_LOADER";
export const UPDATE_NUMBER_OF_DAYS_FOR_FORECAST =
  "UPDATE_NUMBER_OF_DAYS_FOR_FORECAST";
//----------------------------------------------------------------------------//
export const UPDATE_SELECTED_DAY_DETAILS = "UPDATE_SELECTED_DAY_DETAILS";
export const RESET_SELECTED_DAY_DETAILS = "RESET_SELECTED_DAY_DETAILS";
